"""remove test

Revision ID: d58032c7f1d0
Revises: fb6fc26cb80a
Create Date: 2025-08-07 13:39:45.066339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58032c7f1d0'
down_revision: Union[str, Sequence[str], None] = 'fb6fc26cb80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
